### ISSUE TITLE
Create a service for allowing people to share their fiddles

### ISSUE THREAD

**Issue by TheRoccoB** [wasdk/WasmFiddle#3]
From an email to Michael:

So the simplest way I can think of to have a submission thing would be to set up an AWS lambda service with an API gateway. Serverless.com has a pretty cool npm package that makes this setup easy. Once you get a submission, the lambda service could just store a bunch of flat text files in S3. 

The api would look like this:

/submit/:id -> submits an id. Maybe this just creates a text file like, a389b.txt to an S3 bucket
/getSubmissions/ -> polls the s3 bucket and returns a list of the submissions in JSON

**Comment by yurydelendik** [comment]
I opened https://github.com/wasdk/WebAssemblyStudio/projects/2#card-7327340 -- will we consider this idea in the new iteration of WasmFiddle at https://github.com/wasdk/WebAssemblyStudio
