### ISSUE TITLE
WasmFiddle can`t work

### ISSUE THREAD

**Issue by licao404** [wasdk/WasmFiddle#7]
![image](https://user-images.githubusercontent.com/20166747/32817134-302a08b6-c9f7-11e7-95b4-d5eaf7e3a7c6.png)

**Comment by mbebenita** [comment]
Thanks for reporting this, it looks like our service is down. We'll investigate.

**Comment by mbebenita** [comment]
@yurydelendik can you take a look at the herokuapp?

**Comment by yurydelendik** [comment]
It fixed itself by restarting the dyno. Closing as fixed. I'll keep monitoring the similar events
