### ISSUE TITLE
Deploy to gh-pages and avoid deploy commits

### ISSUE THREAD

**Issue by eosrei** [wasdk/WasmFiddle#8]
Feature Suggestion? You can avoid the deploy commits (https://github.com/wasdk/WasmFiddle/commit/c398d17c02cebcf4b9eec8cae26f818af103fa7c and https://github.com/wasdk/WasmFiddle/commit/a410bb54179b01ac1a5646daa21314649b6b1cb4) if you deploy to a `gh-pages` branch. Can be automated with: https://github.com/X1011/git-directory-deploy It's even possible to do CI/CD with TravisCI or CircleCI.

**Comment by yurydelendik** [comment]
We will keep that in mind when we decide to deploy to gh-pages (or other location). Thank you for suggestion. Closing as answered.
